FROM node:20-alpine AS build

WORKDIR /app

ARG VITE_API_URL=
ENV VITE_API_URL=$VITE_API_URL
ARG VITE_APP_TITLE=Oiai
ENV VITE_APP_TITLE=$VITE_APP_TITLE
ARG VITE_APP_DESCRIPTION=Oiai - sua plataforma de compras
ENV VITE_APP_DESCRIPTION=$VITE_APP_DESCRIPTION

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine

ENV NODE_ENV=production

COPY nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
