version: "3.3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: oiai-app
        ports:
            - "8001:80"
            - "5173:5173"
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        command: sh -c "npm run dev & apache2-foreground"
        environment:
            - APACHE_RUN_USER=www-data
            - APACHE_RUN_GROUP=www-data
        depends_on:
            - db

    db:
        image: mysql:5.7
        container_name: oiai-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: oiai
            MYSQL_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"

    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        ports:
            - "1025:1025"
            - "8025:8025"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8080:80"
        depends_on:
            - db

    react:
        build:
            context: ../oiai-front
            dockerfile: Dockerfile
        container_name: oiai-front
        ports:
            - "8081:3000"
        volumes:
            - ./oiai-front:/app
        working_dir: /app
        stdin_open: true
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true

volumes:
    dbdata:
